//---------------------------Group endpoints-------------------

GET http://localhost:4000/groups

###
POST http://localhost:4000/groups
Content-Type: application/json

{
    "groupid":"group6",
    "groupleader":[
        {
            "studentid":"leaderid",
            "name":"leadername",
            "specialization":"specialization"
        }
    ],
    "membertwo":[
        {
            "studentid":"membertwo",
            "name":"name",
            "specialization":"specialization"
        }
    ],
    "memberthree":[
        {
            "studentid":"memberthree",
            "name":"name",
            "specialization":"specialization"
        }
    ],
    "memberfour":[
        {
            "studentid":"memberfour",
            "name":"name",
            "specialization":"specialization"
        }
    ],
    "topic":"topic",
    "topicApproved":"topicApproved",
    "researchGroup":"researchGroup",
    "researchArea":"researchArea",
    "supervisor":"supervisor5",
    "cosupervisor":"cosupervisor5"
}

###
GET http://localhost:4000/groups/supervisor/supervisor5

###
GET http://localhost:4000/groups/cosupervisor/cosupervisor5