# //---------------------------Group endpoints-------------------

# GET http://localhost:4000/groups

# ###
# POST http://localhost:4000/groups
# Content-Type: application/json

# {
#     "groupid":"group6",
#     "topic":"topic",
#     "supervisor":"supervisor",
#     "cosupervisor":"cosupervisor",
#     "groupleaderid":"groupleaderid",
#     "groupleadername":"groupleadername",
#     "membertwoid":"membertwoid",
#     "membertwoname":"membertwoname",
#     "memberthreeid":"memberthreeid",
#     "memberthreename":"memberthreename",
#     "memberfourid":"memberfourid",
#     "memberfourname":"memberfourname"
# }

# ###
# GET http://localhost:4000/groups/supervisor/supervisor5

# ###
# GET http://localhost:4000/groups/cosupervisor/cosupervisor5

# ###
# PATCH http://localhost:4000/groups/628c3f378323683e9e1f1382
# Content-Type: application/json

# {
#     "topicApproved":"Pending"
# }

# //-----------Marking endpoints----------------
# ###
# GET http://localhost:4000/markings

# ###
# POST http://localhost:4000/markings
# Content-Type: application/json

# {
#     "schemaType":"schemaType3",
#     "groupmarkings":[
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         },
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         }
#     ],
#     "individualmarkings":[
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         },
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         }
#     ]

# }

# ###
# GET http://localhost:4000/markings/getmarking/schemaType3

# POST http://localhost:4000/topicregister
# Content-Type: application/json

# {
#     "groupid" : "group1",
#      "topic":"topic",
#     "researchGroup":"ACC",
#      "researchArea":"Robotics",
#      "supervisor":"Dr Parker",
#      "cosupervisor":"Dr peter",
#      "leadername" : "kamal",
#      "itnumber" : "it19979656",
#      "email" : "kamal@gmail.com"

# }

# ###
# GET http://localhost:4000/markings/getmarking/schemaType3

# //---------------------Evaluations----------------------------
# ###
# POST http://localhost:4000/evaluations
# Content-Type: application/json

# {
#     "evaluationType":"test",
#     "groupIdentifier":"groupIdentifier",
#     "groupid":"groupid",
#     "groupmarks":[
#         {
#             "area":"Test123",
#             "marks":"Test"
#         },
#         {
#             "area":"Test123",
#             "marks":"Test"
#         }
#     ],
#     "groupleader":[
#         {
#             "area":"Test123",
#             "marks":"Test"
#         },
#         {
#             "area":"Test123",
#             "marks":"Test"
#         }
#     ],
#     "membertwo":[
#         {
#             "area":"Test123",
#             "marks":"Test"
#         },
#         {
#             "area":"Test123",
#             "marks":"Test"
#         }
#     ],
#     "memberthree":[
#         {
#             "area":"Test123",
#             "marks":"Test"
#         },
#         {
#             "area":"Test123",
#             "marks":"Test"
#         }
#     ],
#     "memberfour":[
#         {
#             "area":"Test123",
#             "marks":"Test"
#         },
#         {
#             "area":"Test123",
#             "marks":"Test"
#         }
#     ]

# }

POST http://localhost:4000/topicregister
Content-Type: application/json

{
    "groupid" : "group1",
     "topic":"topic",
    "researchGroup":"ACC",
     "researchArea":"Robotics",
     "supervisor":"Dr Parker",
     "cosupervisor":"Dr peter",
     "leadername" : "kamal",
     "itnumber" : "it19979656",
     "email" : "kamal@gmail.com"



}

###
GET http://localhost:4000/markings/getmarking/schemaType3

//---------------------Evaluations----------------------------
###
POST http://localhost:4000/evaluations
Content-Type: application/json

{
    "evaluationType":"test",
    "groupIdentifier":"groupIdentifier",
    "groupid":"groupid",
    "groupmarks":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "groupleader":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "membertwo":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "memberthree":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "memberfour":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ]

}

# ###
# GET http://localhost:4000/evaluations


# POST http://localhost:4000/supervisors/savesupervisors
# Content-Type: application/json

# {
#      "supervisor_name":"Dr kamal",
#      "specialization":"AI",
#      "email":"kamal.sliit@outlook.com"
     
# }

# GET http://localhost:4000/supervisors


# POST http://localhost:4000/topicregister/creategroup
# Content-Type: application/json

# {
#     "groupid":"group6",
#     "members" : [
#         "6296facab996c21294bea6df",
#         "6296fb02b996c21294bea6e5"
       
#     ]
# }

GET http://localhost:4000/topicregister/getstudents/6296fb02b996c21294bea6e5

# GET http://localhost:4000/topicregister/getstudents

###
GET http://localhost:4000/adminUsers/getpresentation

#PATCH http://localhost:4000/adminUsers/6292f5e1fc2eddb6492e2297
#Content-Type: application/json

#{
#    "name" : "Kavindu",
#    "role":"Student",
#    "specialisation":"None"    
#}


# DELETE  http://localhost:4000/adminUsers/6292f46375a4bb1f4ab11fe6

PATCH  http://localhost:4000/adminUsers/updateviva/6296fccde5351d24b235598e
Content-Type: application/json

{
       "Attributes": "Hello",
        "marks": 88 
}
  


###
POST http://localhost:4000/evaluations
Content-Type: application/json


{
    "groupid":"grp123",
    "evaluationtype":"evaluationtype",
    "groupmark":"groupmark",
    "groupleaderid":"groupleaderid",
    "groupleadermark":"groupleadermark",
    "membertwoid":"membertwoid",
    "membertwomark":"membertwomark",
    "memberthreeid":"memberthreeid",
    "memberthreemark":"memberthreemark",
    "memberfourid":"memberfourid",
    "memberfourmark":"memberfourmark",
    "comments":"comments"
}

###
POST http://localhost:4000/requests
Content-Type: application/json

{
    "groupid":"GRP_03_WE_2022",
    "topic":"Cultural expectations and practices",
    "description":"Cultural expectations are the messages we internalize about what is and is not acceptable, given the standards of behavior and cultural norms put forth by our social systems. Social groups come in many forms, including our family, community, friends, workplace, and even affinity groups.",
    "requestedSupervisor":"Saman",
    "requestedCosupervisor":"requestedCosupervisor",
    "stateSupervisor":"Pending",
    "stateCoSupervisor":"stateCoSupervisor"
}

###
GET http://localhost:4000/requests/supervisor/requestedSupervisor

###
PATCH http://localhost:4000/requests/62990e694b16a8594043977a
Content-Type: application/json

{
    "stateSupervisor":"Approved"
}

###
GET http://localhost:4000/markings/viva

###
GET http://localhost:4000/markings/document