# //---------------------------Group endpoints-------------------

# GET http://localhost:4000/groups

# ###
# POST http://localhost:4000/groups
# Content-Type: application/json

# {
#     "groupid":"group6",
#     "groupleader":[
#         {
#             "studentid":"leaderid",
#             "name":"leadername",
#             "specialization":"specialization"
#         }
#     ],
#     "membertwo":[
#         {
#             "studentid":"membertwo",
#             "name":"name",
#             "specialization":"specialization"
#         }
#     ],
#     "memberthree":[
#         {
#             "studentid":"memberthree",
#             "name":"name",
#             "specialization":"specialization"
#         }
#     ],
#     "memberfour":[
#         {
#             "studentid":"memberfour",
#             "name":"name",
#             "specialization":"specialization"
#         }
#     ],
#     "topic":"topic",
#     "topicApproved":"topicApproved",
#     "researchGroup":"researchGroup",
#     "researchArea":"researchArea",
#     "supervisor":"supervisor5",
#     "cosupervisor":"cosupervisor5"
# }

# ###
# GET http://localhost:4000/groups/supervisor/supervisor5

# ###
# GET http://localhost:4000/groups/cosupervisor/cosupervisor5

# ###
# PATCH http://localhost:4000/groups/628c3f378323683e9e1f1382
# Content-Type: application/json

# {
#     "topicApproved":"Pending"
# }

# //-----------Marking endpoints----------------
# ###
# GET http://localhost:4000/markings

# ###
# POST http://localhost:4000/markings
# Content-Type: application/json

# {
#     "schemaType":"schemaType3",
#     "groupmarkings":[
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         },
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         }
#     ],
#     "individualmarkings":[
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         },
#         {
#             "area":"Test123",
#             "highestmarks":"Test"
#         }
#     ]

# }

# ###
# GET http://localhost:4000/markings/getmarking/schemaType3

POST http://localhost:4000/topicregister
Content-Type: application/json

{
    "groupid" : "group1",
     "topic":"topic",
    "researchGroup":"ACC",
     "researchArea":"Robotics",
     "supervisor":"Dr Parker",
     "cosupervisor":"Dr peter",
     "leadername" : "kamal",
     "itnumber" : "it19979656",
     "email" : "kamal@gmail.com"



}

###
GET http://localhost:4000/markings/getmarking/schemaType3

//---------------------Evaluations----------------------------
###
POST http://localhost:4000/evaluations
Content-Type: application/json

{
    "evaluationType":"test",
    "groupIdentifier":"groupIdentifier",
    "groupid":"groupid",
    "groupmarks":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "groupleader":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "membertwo":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "memberthree":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ],
    "memberfour":[
        {
            "area":"Test123",
            "marks":"Test"
        },
        {
            "area":"Test123",
            "marks":"Test"
        }
    ]

}

# ###
# GET http://localhost:4000/evaluations

###
GET http://localhost:4000/adminUsers/userup/6296facab996c21294bea6df

#PATCH http://localhost:4000/adminUsers/6292f5e1fc2eddb6492e2297
#Content-Type: application/json

#{
#    "name" : "Kavindu",
#    "role":"Student",
#    "specialisation":"None"    
#}


# DELETE  http://localhost:4000/adminUsers/6292f46375a4bb1f4ab11fe6

###
POST   http://localhost:4000/adminUsers/presenatation
Content-Type: application/json

{
       "Attributes": "Hello",
        "marks": 88 
}
   

